version: "3.7"
services:
  node:
    build: .
    ports:
      - "8080:80"
    volumes:
      - "/d/work/front-end-development/src/docker/compose/code:/code"
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - "/d/work/front-end-development/src/docker/compose/nginx.conf:/etc/nginx/nginx.conf"
      - "/d/work/front-end-development/src/docker/compose/logs:/var/log/nginx"
